# Generated by Django 6.0.6 on 2026-06-23 05:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InwardGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_number', models.CharField(max_length=30, unique=True, verbose_name='Gate Pass No.')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Supplier / Party Name')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, verbose_name='Vehicle No.')),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_cnic', models.CharField(blank=True, max_length=20, verbose_name='Driver CNIC')),
                ('received_by', models.CharField(blank=True, max_length=150)),
                ('security_officer', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.purchaseorder', verbose_name='PO Reference')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier')),
            ],
            options={
                'verbose_name': 'Inward Gate Pass',
                'verbose_name_plural': 'Inward Gate Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InwardGatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight (Kg)')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gatepass.inwardgatepass')),
            ],
            options={
                'verbose_name': 'Gate Pass Item',
            },
        ),
    ]
