# Generated by Django 6.0.6 on 2026-06-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0001_inward_gate_pass'),
        ('sales', '0006_credit_note_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inwardgatepassitem',
            options={'verbose_name': 'Inward Gate Pass Item'},
        ),
        migrations.CreateModel(
            name='OutwardGatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gate_pass_number', models.CharField(max_length=30, unique=True, verbose_name='Gate Pass No.')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('purpose', models.CharField(choices=[('sale', 'Customer Sale / Delivery'), ('return', 'Return to Supplier'), ('transfer', 'Internal Transfer'), ('sample', 'Sample / Demo'), ('other', 'Other')], default='sale', max_length=20)),
                ('party_name', models.CharField(blank=True, max_length=255, verbose_name='Customer / Party Name')),
                ('destination', models.CharField(blank=True, max_length=255, verbose_name='Destination / Address')),
                ('vehicle_number', models.CharField(blank=True, max_length=50, verbose_name='Vehicle No.')),
                ('driver_name', models.CharField(blank=True, max_length=150)),
                ('driver_cnic', models.CharField(blank=True, max_length=20, verbose_name='Driver CNIC')),
                ('invoice_ref', models.CharField(blank=True, max_length=50, verbose_name='Invoice / DO Reference')),
                ('dispatched_by', models.CharField(blank=True, max_length=150)),
                ('security_officer', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer')),
            ],
            options={
                'verbose_name': 'Outward Gate Pass',
                'verbose_name_plural': 'Outward Gate Passes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutwardGatePassItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight (Kg)')),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('gate_pass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gatepass.outwardgatepass')),
            ],
            options={
                'verbose_name': 'Outward Gate Pass Item',
            },
        ),
    ]
