# Generated by Django 6.0.6 on 2026-06-22 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_province_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Cancellation / Credit Note Reason'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_credit_note',
            field=models.BooleanField(default=False, verbose_name='Is Credit Note'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='original_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='sales.invoice', verbose_name='Original Invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fbr_error',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fbr_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
